# Generated by Django 3.0.6 on 2020-05-11 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('awb_no', models.CharField(blank=True, max_length=16, null=True)),
                ('record_no', models.CharField(blank=True, max_length=16, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_acm', to=settings.AUTH_USER_MODEL)),
                ('awb_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_awb_image', to='photo.Photo')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_distributor', to='distributors.Distributor')),
                ('finance_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_finance_manager', to=settings.AUTH_USER_MODEL)),
                ('record_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_record_image', to='photo.Photo')),
            ],
        ),
    ]
