# Generated by Django 3.0.6 on 2020-09-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_warninglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='distributor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_type', to='distributors.DistributorType'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='total_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='visit_frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=7),
        ),
    ]
