# Generated by Django 3.0.6 on 2020-09-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0004_auto_20200907_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
