# Generated by Django 3.0.6 on 2020-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0007_distributorwarning_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorwarning',
            name='account_is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributorwarning',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributorwarning',
            name='type',
            field=models.CharField(choices=[('gen', 'Generated'), ('frc', 'Force Generated')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='distributorwarning',
            name='status',
            field=models.IntegerField(choices=[(100, 'Pending'), (200, 'QA Approved'), (300, 'Account Approved'), (500, 'Finance Approved'), (1000, 'Rejected')], null=True),
        ),
    ]
