# Generated by Django 3.0.6 on 2020-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0008_auto_20201108_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warninglog',
            name='type',
            field=models.CharField(choices=[('inf', 'Info'), ('scs', 'Success'), ('err', 'Error'), ('wrn', 'Warning')], default=None, max_length=3),
        ),
    ]
