# Generated by Django 3.0.6 on 2020-11-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_delete_warningnotification'),
        ('distributors', '0009_auto_20201108_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorwarning',
            name='notifications',
            field=models.ManyToManyField(to='inspections.InspectionNotification'),
        ),
    ]
