# Generated by Django 3.0.6 on 2021-01-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0010_distributorwarning_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='distributor_key',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
