# Generated by Django 3.0.6 on 2020-05-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_warninglog'),
        ('inspections', '0003_inspectionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wn_warning', to='distributors.DistributorWarning')),
                ('inspection_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wn_inspection_notification', to='inspections.InspectionNotification')),
            ],
        ),
    ]
