# Generated by Django 3.0.6 on 2020-09-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_warningnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='inspections.Inspection'),
        ),
    ]
