# Generated by Django 3.0.6 on 2020-09-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_auto_20200907_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='total_mark',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
