# Generated by Django 3.0.6 on 2020-09-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_auto_20200908_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='total_mark',
            field=models.IntegerField(default=0),
        ),
    ]
