# Generated by Django 3.0.6 on 2020-09-09 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_auto_20200908_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='date_initial',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
