# Generated by Django 3.0.6 on 2020-09-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_inspection_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.IntegerField(choices=[(100, 'Pending'), (200, 'Incomplete'), (220, 'Reassigned'), (240, 'Notified'), (300, 'Completed'), (400, 'Supervisor Approved'), (600, 'Supervisor Declined'), (1000, 'Deleted')], null=True),
        ),
    ]
