# Generated by Django 3.0.6 on 2020-10-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_auto_20200921_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-updated']},
        ),
    ]
