# Generated by Django 3.0.6 on 2020-10-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_auto_20201018_0342'),
        ('inspections', '0010_auto_20201013_1212'),
    ]

    operations = [
    ]
