# Generated by Django 3.0.6 on 2020-10-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_auto_20201021_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
