# Generated by Django 3.0.6 on 2020-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_auto_20201021_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionlog',
            name='type',
            field=models.CharField(choices=[('inf', 'Info'), ('scs', 'Success'), ('err', 'Error'), ('wrn', 'Warning')], default=None, max_length=3),
        ),
    ]
