# Generated by Django 3.0.6 on 2020-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_auto_20201022_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='account_is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='finance_is_read',
            field=models.BooleanField(default=False),
        ),
    ]
