# Generated by Django 3.0.6 on 2020-11-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_auto_20201105_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WarningNotification',
        ),
    ]
